default: &DEFAULT
  adapter: postgresql
  encoding: utf8

development:
  <<: *DEFAULT
  database:  simple_web_rg_dev
  host:      localhost

production:
  <<: *DEFAULT
  url: <%= ENV['DATABASE_URL'] %>
