User.create(name: 'Michael Scott', job_title: 'Regional Manager')
User.create(name: 'Dwight Schrute', job_title: 'Assistant to the Regional Manager')
User.create(name: 'Jim Halpert', job_title: 'Salesperson')
User.create(name: 'Pam Beasley', job_title: 'Receptionist')
User.create(name: 'Kevin Malone', job_title: 'Accountant')
